import Router from 'koa-router'
import { Success } from '../../../../core/HttpException'

const router = new Router({
  prefix: '/api/v1/lowCode/componentCategoryManager',
})

/*
 * 新增看板
 * @return
 */
router.get('/getDM', async () => {
  const data = {
    measures: [
      {
        id: '95',
        name: 'bycgje',
        enName: 'bycgje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'bycgje',
      },
      {
        id: '96',
        name: 'cgbyfkje',
        enName: 'cgbyfkje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'cgbyfkje',
      },
      { id: '97', name: 'cp1hk', enName: 'cp1hk', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'cp1hk' },
      {
        id: '98',
        name: 'cp1xsje',
        enName: 'cp1xsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'cp1xsje',
      },
      { id: '99', name: 'cp2hk', enName: 'cp2hk', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'cp2hk' },
      {
        id: '100',
        name: 'cp2xsje',
        enName: 'cp2xsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'cp2xsje',
      },
      { id: '101', name: 'hk', enName: 'hk', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'hk' },
      { id: '102', name: 'hkje', enName: 'hkje', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'hkje' },
      {
        id: '103',
        name: 'hkjekymb',
        enName: 'hkjekymb',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'hkjekymb',
      },
      {
        id: '104',
        name: 'hkjejk',
        enName: 'hkjejk',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'hkjejk',
      },
      {
        id: '105',
        name: 'jhyjje',
        enName: 'jhyjje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'jhyjje',
      },
      {
        id: '106',
        name: 'jsfwhk',
        enName: 'jsfwhk',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'jsfwhk',
      },
      {
        id: '107',
        name: 'jsfwxsje',
        enName: 'jsfwxsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'jsfwxsje',
      },
      { id: '108', name: 'kpe', enName: 'kpe', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'kpe' },
      {
        id: '109',
        name: 'lkhfgxsje',
        enName: 'lkhfgxsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'lkhfgxsje',
      },
      {
        id: '110',
        name: 'qtbdhk',
        enName: 'qtbdhk',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'qtbdhk',
      },
      {
        id: '111',
        name: 'qtbdxsje',
        enName: 'qtbdxsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'qtbdxsje',
      },
      {
        id: '112',
        name: 'qdxsje',
        enName: 'qdxsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'qdxsje',
      },
      {
        id: '113',
        name: 'sscgbyfkje',
        enName: 'sscgbyfkje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'sscgbyfkje',
      },
      { id: '114', name: 'sscbk', enName: 'sscbk', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'sscbk' },
      {
        id: '115',
        name: 'ssfgxsje',
        enName: 'ssfgxsje',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'ssfgxsje',
      },
      { id: '116', name: 'sshk', enName: 'sshk', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'sshk' },
      { id: '117', name: 'ssje', enName: 'ssje', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'ssje' },
      { id: '118', name: 'xse', enName: 'xse', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'xse' },
      { id: '119', name: 'xsje', enName: 'xsje', originColType: 'UInt32', colType: 'INT', source: 4, dname: 'xsje' },
      {
        id: '120',
        name: 'xsjekymb',
        enName: 'xsjekymb',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'xsjekymb',
      },
      {
        id: '121',
        name: 'xsjejk',
        enName: 'xsjejk',
        originColType: 'UInt32',
        colType: 'INT',
        source: 4,
        dname: 'xsjejk',
      },
      {
        id: '-1',
        name: '记录数',
        enName: 'recorder',
        originColType: 'INT',
        colType: 'INT',
        source: 5,
        dname: '记录数',
      },
    ],
    dimensions: [
      {
        id: '88',
        name: 'count_date',
        enName: 'count_date',
        originColType: 'DateTime',
        colType: 'DATETIME',
        source: 4,
        dname: 'count_date',
      },
      { id: '89', name: 'gszq', enName: 'gszq', originColType: 'String', colType: 'STRING', source: 4, dname: 'gszq' },
      { id: '90', name: 'xsqd', enName: 'xsqd', originColType: 'String', colType: 'STRING', source: 4, dname: 'xsqd' },
      { id: '91', name: 'xsxz', enName: 'xsxz', originColType: 'String', colType: 'STRING', source: 4, dname: 'xsxz' },
      { id: '92', name: 'ygxz', enName: 'ygxz', originColType: 'String', colType: 'STRING', source: 4, dname: 'ygxz' },
      { id: '93', name: 'zzzt', enName: 'zzzt', originColType: 'String', colType: 'STRING', source: 4, dname: 'zzzt' },
      { id: '94', name: 'zj', enName: 'zj', originColType: 'String', colType: 'STRING', source: 4, dname: 'zj' },
    ],
  }
  throw new Success(data)
})

export default router
