import Router from 'koa-router'
import Config from '../../../../config/Config'
import { Success } from '../../../../core/HttpException'

const router = new Router({
  prefix: `${Config.API_PREFIX}v1/lowCode/board`,
})

/*
  查看看板、分类树型结构
 * @return
 */
router.get('/getDashboardAndCategoryTreeByType', async () => {
  const data = [
    {
      id: 0,
      businessId: '',
      parentId: -1,
      treeType: '',
      children: [
        {
          id: 5,
          businessId: '',
          parentId: 0,
          treeType: '',
          children: [],
          name: '测试分类',
          enName: '',
          describe: '',
          rootId: '',
          categoryLevel: '',
          subDataElementCount: '',
          treeObj: [
            {
              id: 38,
              name: 'aaa',
              description: '',
              dasDashboardCategoryId: 5,
              pathLevel: '5',
              pageOperation:
                '{"componentList":[{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[]},"linkage":{"componentList":[]},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":99,"top":99},"id":"widget","tag":"c-widget","label":"新新组件测试","icon":"table","props":{"widgetType":"Table","value":{"id":131,"name":"新新组件测试","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":4,"chartStyle":"{\\"globeStyle\\":\\"\\", \\"seriesStyle\\":\\"\\"}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[{\\"name\\":\\"cp1hk\\",\\"enName\\":\\"cp1hk\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"97\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2}],\\"timeStamp\\":1645169005176,\\"pageNum\\":1,\\"pageSize\\":999999,\\"chartType\\":4,\\"type\\":1}","status":0,"del":0,"createUser":"liang","createTime":"2022-02-18 15:21:50","updateUser":"","updateTime":"","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"柱状图","chartEnName":"HISTOGRAM","chartDescription":"","chartTips":"柱状图:","chartTypeId":"4","componentCategoryId":"2","componentCategoryName":"分类1","params":{"chartType":4,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[{"name":"cp1hk","enName":"cp1hk","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"97","colType":"INT","order":0,"origin":0,"type":2}],"globalFilter":[],"name":"新新组件测试","pageNum":1,"pageSize":10,"timeStamp":1645171893007,"type":1},"componentPageId":"widget607555"},"loading":false,"filterKeys":[],"updateComponent":0,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget607555"}],"pageSetting":{"width":1300,"height":700,"title":"大数据可视化看板","backgroundColor":"#e1dfdf","backgroundImage":"","backgroundSize":"100% 100%","backgroundPosition":"center center","backgroundRepeat":"repeat","globalTitleStyle":{"fontFamily":""},"isGrid":true}}',
              status: 0,
              publishTime: '',
              del: 0,
              createUser: 'niewanjun',
              createTime: '2022-02-18 15:38:15',
              updateUser: 'niewanjun',
              updateTime: '2022-02-18 16:13:07',
              itemList: [
                {
                  id: 383,
                  quoteChartId: '',
                  dasDashboardId: 38,
                  name: '新新组件测试',
                  type: 2,
                  componentType: 1,
                  categoryId: 2,
                  datasourceId: 105,
                  tableName: 'zt_rk_xsb',
                  tableCode: 'zt_rk_xsb40',
                  databaseName: 'default',
                  dataGradeThematicId: 5,
                  chartTypeId: 4,
                  chartStyle: '{"globeStyle":"", "seriesStyle":""}',
                  chartAxisData:
                    '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[{"name":"cp1hk","enName":"cp1hk","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"97","colType":"INT","order":0,"origin":0,"type":2}],"timeStamp":1645169005176,"pageNum":1,"pageSize":999999,"chartType":4,"type":1}',
                  del: 0,
                  componentPageId: 'widget607555',
                  createUser: 'niewanjun',
                  createTime: '2022-02-18 16:13:07',
                  updateUser: 'niewanjun',
                  updateTime: '2022-02-18 16:13:07',
                  tenantId: 1,
                },
              ],
              dasLabelList: '',
            },
          ],
          leaf: true,
        },
      ],
      name: '全部',
      enName: '',
      describe: '',
      rootId: 0,
      categoryLevel: '',
      subDataElementCount: '',
      treeObj: [
        {
          id: 39,
          name: '测试',
          description: '11',
          dasDashboardCategoryId: 0,
          pathLevel: '',
          pageOperation:
            '{"componentList":[{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[]},"linkage":{"componentList":[]},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":true,"isStyle":true,"isEvent":false,"isLinkage":false,"isJump":false,"id":"select","tag":"c-select","label":"下拉列表","props":{"filterField":[],"title":"下拉选择","options":[],"mode":"default","isPreview":false},"isSetAttr":true,"dataTabel":"select","type":"select","icon":"unordered-list","style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":200,"height":34,"backgroundColor":"#fff","left":28,"top":19},"key":"select202310"},{"animations":[],"events":{"click":"handleSubmit"},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[]},"linkage":{"componentList":[]},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":true,"isStyle":true,"isEvent":false,"isLinkage":false,"isJump":false,"id":"button","tag":"c-button","label":"查询按钮","text":"查询","props":{"title":"查询","isPreview":false},"type":"button","icon":"search","style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":100,"height":34,"type":"primary","left":320,"top":19},"key":"button445387"},{"animations":[],"events":{"click":"handleReset"},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[]},"linkage":{"componentList":[]},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":true,"isStyle":true,"isEvent":false,"isLinkage":false,"isJump":false,"id":"button","tag":"c-button","label":"重置按钮","text":"重置","props":{"title":"重置","isPreview":false},"type":"button","icon":"sync","style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":100,"height":34,"type":"default","left":428,"top":19},"key":"button111213"},{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[],"isEnable":false},"linkage":{"componentList":[{"key":"widget460767","name":"新折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget128255","name":"面积图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget448001","name":"测试条形图","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"bycgje","value":"bycgje","colType":"INT","id":"95","filterType":2},{"type":"field","label":"cp1hk","value":"cp1hk","colType":"INT","id":"97","filterType":2}],"isCheck":false},{"key":"widget94350","name":"折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1}],"isCheck":false}],"isEnable":false},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":28,"top":65},"id":"widget","tag":"c-widget","label":"测试432432","icon":"table","props":{"widgetType":"Table","value":{"id":142,"name":"测试432432","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":4,"chartStyle":"{\\"globeStyle\\":{\\"data\\":[],\\"title\\":{\\"name\\":\\"柱状图2\\",\\"style\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":\\"16px\\"}},\\"option\\":{\\"xAxis\\":{\\"gridIndex\\":0,\\"show\\":true,\\"position\\":\\"bottom\\",\\"type\\":\\"category\\",\\"name\\":\\"\\",\\"nameTextStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12,\\"color\\":\\"#000000\\"},\\"nameLocation\\":\\"\\",\\"data\\":[],\\"axisLine\\":{\\"show\\":true},\\"splitLine\\":{\\"show\\":true},\\"axisTick\\":{\\"show\\":true,\\"length\\":14}},\\"tooltip\\":{\\"trigger\\":\\"axis\\",\\"axisPointer\\":{\\"type\\":\\"shadow\\"}},\\"yAxis\\":{\\"show\\":true,\\"position\\":\\"top\\",\\"type\\":\\"value\\",\\"name\\":\\"\\",\\"nameLocation\\":\\"\\",\\"nameTextStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12,\\"color\\":\\"#000000\\"},\\"axisLine\\":{\\"show\\":true},\\"splitLine\\":{\\"show\\":true},\\"axisTick\\":{\\"show\\":true}},\\"legend\\":{\\"show\\":false,\\"left\\":\\"center\\",\\"right\\":\\"auto\\",\\"top\\":\\"top\\",\\"bottom\\":\\"auto\\",\\"width\\":\\"auto\\",\\"height\\":\\"auto\\",\\"orient\\":\\"horizontal\\",\\"textStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12}},\\"series\\":[],\\"backgroundColor\\":\\"transparent\\"}},\\"seriesStyle\\":{\\"cgbyfkje\\":{\\"label\\":{\\"show\\":true,\\"position\\":\\"top\\",\\"rotate\\":0,\\"offset\\":[0,0]},\\"seriesItemStyle\\":{\\"opacity\\":1,\\"color\\":\\"rgba(9,249,157,1)\\",\\"borderRadius\\":[0,0,0,0]}}}}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[{\\"name\\":\\"cgbyfkje\\",\\"enName\\":\\"cgbyfkje\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"96\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2}],\\"timeStamp\\":1645174345563,\\"pageNum\\":1,\\"pageSize\\":999999,\\"chartType\\":4,\\"type\\":1}","status":0,"del":0,"createUser":"liang","createTime":"2022-02-18 16:51:01","updateUser":"","updateTime":"","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"柱状图","chartEnName":"HISTOGRAM","chartDescription":"","chartTips":"柱状图:","chartTypeId":"4","componentCategoryId":"2","componentCategoryName":"分类1","params":{"chartType":4,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"globalFilter":[],"name":"测试432432","pageNum":1,"pageSize":10,"timeStamp":1645690110746,"type":1},"quoteChartId":142,"componentPageId":"widget776697"},"loading":false,"filterKeys":[],"updateComponent":1,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget776697"},{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[],"isEnable":false},"linkage":{"componentList":[{"key":"widget776697","name":"测试432432","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget128255","name":"面积图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget448001","name":"测试条形图","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"bycgje","value":"bycgje","colType":"INT","id":"95","filterType":2},{"type":"field","label":"cp1hk","value":"cp1hk","colType":"INT","id":"97","filterType":2}],"isCheck":false},{"key":"widget94350","name":"折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1}],"isCheck":false}],"isEnable":false},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":548,"top":65},"id":"widget","tag":"c-widget","label":"新折线图测试","icon":"table","props":{"widgetType":"Table","value":{"id":139,"name":"新折线图测试","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":12,"chartStyle":"{\\"globeStyle\\":{\\"data\\":[],\\"title\\":{\\"name\\":\\"折线图\\",\\"style\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":\\"16px\\"}},\\"option\\":{\\"color\\":[],\\"xAxis\\":{\\"gridIndex\\":0,\\"show\\":true,\\"position\\":\\"bottom\\",\\"type\\":\\"category\\",\\"name\\":\\"\\",\\"nameTextStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12,\\"color\\":\\"#000000\\"},\\"nameLocation\\":\\"\\",\\"data\\":[],\\"axisLine\\":{\\"show\\":true},\\"splitLine\\":{\\"show\\":true},\\"axisTick\\":{\\"show\\":true,\\"length\\":14}},\\"tooltip\\":{\\"trigger\\":\\"axis\\",\\"axisPointer\\":{\\"type\\":\\"shadow\\"}},\\"yAxis\\":{\\"show\\":true,\\"position\\":\\"top\\",\\"type\\":\\"value\\",\\"name\\":\\"\\",\\"nameLocation\\":\\"\\",\\"nameTextStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12,\\"color\\":\\"#000000\\"},\\"axisLine\\":{\\"show\\":true},\\"splitLine\\":{\\"show\\":true},\\"axisTick\\":{\\"show\\":true}},\\"legend\\":{\\"show\\":false,\\"left\\":\\"center\\",\\"right\\":\\"auto\\",\\"top\\":\\"top\\",\\"bottom\\":\\"auto\\",\\"width\\":\\"auto\\",\\"height\\":\\"auto\\",\\"orient\\":\\"horizontal\\",\\"textStyle\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":12}},\\"series\\":[],\\"backgroundColor\\":\\"transparent\\"}},\\"seriesStyle\\":{\\"cgbyfkje\\":{\\"label\\":{\\"show\\":true,\\"position\\":\\"top\\",\\"rotate\\":0,\\"offset\\":[0,0]},\\"seriesItemStyle\\":{\\"opacity\\":1,\\"color\\":\\"#c23531\\",\\"borderRadius\\":[0,0,0,0]},\\"itemStyle\\":{\\"opacity\\":1,\\"color\\":\\"#c23531\\",\\"borderRadius\\":[0,0,0,0]}}}}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[{\\"name\\":\\"cgbyfkje\\",\\"enName\\":\\"cgbyfkje\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"96\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2}],\\"timeStamp\\":1645173767363,\\"pageNum\\":1,\\"pageSize\\":999999,\\"chartType\\":12,\\"type\\":1}","status":0,"del":0,"createUser":"liang","createTime":"2022-02-18 16:41:24","updateUser":"","updateTime":"","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"折线图","chartEnName":"LINE_CHAR","chartDescription":"","chartTips":"折线图:","chartTypeId":"12","componentCategoryId":"2","componentCategoryName":"分类1","params":{"chartType":12,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"globalFilter":[],"name":"新折线图测试","pageNum":1,"pageSize":10,"timeStamp":1645690110746,"type":1},"quoteChartId":139,"componentPageId":"widget460767"},"loading":false,"filterKeys":[],"updateComponent":1,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget460767"},{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[],"isEnable":false},"linkage":{"componentList":[{"key":"widget776697","name":"测试432432","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget460767","name":"新折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget448001","name":"测试条形图","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"bycgje","value":"bycgje","colType":"INT","id":"95","filterType":2},{"type":"field","label":"cp1hk","value":"cp1hk","colType":"INT","id":"97","filterType":2}],"isCheck":false},{"key":"widget94350","name":"折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1}],"isCheck":false}],"isEnable":false},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":28,"top":388},"id":"widget","tag":"c-widget","label":"面积图测试","icon":"table","props":{"widgetType":"Table","value":{"id":140,"name":"面积图测试","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":13,"chartStyle":"{\\"globeStyle\\":\\"\\", \\"seriesStyle\\":\\"\\"}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[{\\"name\\":\\"cgbyfkje\\",\\"enName\\":\\"cgbyfkje\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"96\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2}],\\"timeStamp\\":1645145434936,\\"pageNum\\":1,\\"pageSize\\":999999,\\"chartType\\":13,\\"type\\":1}","status":0,"del":0,"createUser":"admin","createTime":"2022-02-18 16:43:59","updateUser":"","updateTime":"","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"面积图","chartEnName":"AREA_LINE_CHAR","chartDescription":"","chartTips":"面积图:","chartTypeId":"13","componentCategoryId":"5","componentCategoryName":"分类4","params":{"chartType":13,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"globalFilter":[],"name":"面积图测试","pageNum":1,"pageSize":10,"timeStamp":1645690110746,"type":1},"quoteChartId":140,"componentPageId":"widget128255"},"loading":false,"filterKeys":[],"updateComponent":0,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget128255"},{"animations":[],"events":{},"jump":{"targetType":"board","openType":"target","isFilter":false,"target":[],"isEnable":false},"linkage":{"componentList":[{"key":"widget776697","name":"测试432432","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":true},{"key":"widget460767","name":"新折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget128255","name":"面积图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget94350","name":"折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1}],"isCheck":false}],"isEnable":true,"source":"gszq"},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":548,"top":388},"id":"widget","tag":"c-widget","label":"测试条形图","icon":"table","props":{"widgetType":"Table","value":{"id":136,"name":"测试条形图","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":6,"chartStyle":"{\\"globeStyle\\":\\"\\", \\"seriesStyle\\":\\"\\"}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[{\\"name\\":\\"bycgje\\",\\"enName\\":\\"bycgje\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"95\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2},{\\"name\\":\\"cp1hk\\",\\"enName\\":\\"cp1hk\\",\\"numFormat\\":{\\"type\\":1,\\"digit\\":0,\\"unit\\":1,\\"suffix\\":\\"\\"},\\"countingRules\\":1,\\"id\\":\\"97\\",\\"colType\\":\\"INT\\",\\"order\\":0,\\"origin\\":0,\\"type\\":2}],\\"timeStamp\\":1645083445300,\\"pageNum\\":1,\\"pageSize\\":999999,\\"chartType\\":6,\\"type\\":1}","status":0,"del":0,"createUser":"admin","createTime":"2022-02-18 16:37:51","updateUser":"","updateTime":"","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"条形图","chartEnName":"BAR_CHART","chartDescription":"","chartTips":"条形图:","chartTypeId":"6","componentCategoryId":"5","componentCategoryName":"分类4","params":{"chartType":6,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[{"name":"bycgje","enName":"bycgje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"95","colType":"INT","order":0,"origin":0,"type":2},{"name":"cp1hk","enName":"cp1hk","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"97","colType":"INT","order":0,"origin":0,"type":2}],"globalFilter":[],"name":"测试条形图","pageNum":1,"pageSize":10,"timeStamp":1645690110747,"type":1},"quoteChartId":136,"componentPageId":"widget448001"},"loading":false,"filterKeys":[],"updateComponent":0,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget448001"},{"animations":[],"events":{},"jump":{"targetType":"board","openType":"self","isFilter":false,"target":[],"isEnable":true,"targetPage":39},"linkage":{"componentList":[{"key":"widget776697","name":"测试432432","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget460767","name":"新折线图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget128255","name":"面积图测试","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"cgbyfkje","value":"cgbyfkje","colType":"INT","id":"96","filterType":2}],"isCheck":false},{"key":"widget448001","name":"测试条形图","options":[{"type":"field","label":"gszq","value":"gszq","colType":"STRING","id":"89","filterType":1},{"type":"field","label":"bycgje","value":"bycgje","colType":"INT","id":"95","filterType":2},{"type":"field","label":"cp1hk","value":"cp1hk","colType":"INT","id":"97","filterType":2}],"isCheck":false}],"isEnable":false},"class":"c-component","isShow":true,"isDrop":false,"isGeometry":true,"isData":false,"isStyle":false,"isEvent":false,"isLinkage":true,"isJump":true,"style":{"opacity":1,"widthUnit":"px","heightUnit":"px","leftUnit":"px","topUnit":"px","width":500,"height":300,"left":285,"top":177},"id":"widget","tag":"c-widget","label":"折线图测试","icon":"table","props":{"widgetType":"Table","value":{"id":138,"name":"折线图测试","type":2,"componentType":1,"datasourceId":105,"tableName":"zt_rk_xsb","databaseName":"default","dataGradeThematicId":5,"tableCode":"zt_rk_xsb40","dasChartTypeId":3,"chartStyle":"{\\"globeStyle\\":{\\"title\\":{\\"name\\":\\"明细表2\\",\\"style\\":{\\"fontFamily\\":\\"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol\\",\\"fontSize\\":\\"16px\\"}},\\"pagination\\":{\\"pageSize\\":20,\\"current\\":1,\\"total\\":533},\\"option\\":{\\"data\\":[],\\"fields\\":{\\"columns\\":[]},\\"meta\\":[]}},\\"seriesStyle\\":\\"\\"}","chartAxisData":"{\\"dataSource\\":{\\"databaseName\\":\\"default\\",\\"datasourceId\\":105,\\"gradeThematicId\\":5,\\"tableName\\":\\"zt_rk_xsb\\",\\"tableCode\\":\\"zt_rk_xsb40\\"},\\"dimensions\\":[{\\"name\\":\\"gszq\\",\\"enName\\":\\"gszq\\",\\"countingRules\\":\\"\\",\\"id\\":\\"89\\",\\"colType\\":\\"STRING\\",\\"order\\":0,\\"origin\\":0,\\"type\\":1}],\\"globalFilter\\":[],\\"measures\\":[],\\"timeStamp\\":1645520509375,\\"pageNum\\":1,\\"dataId\\":138,\\"name\\":\\"折线图测试\\",\\"pageSize\\":20,\\"chartType\\":3,\\"type\\":1}","status":0,"del":0,"createUser":"admin","createTime":"2022-02-18 16:39:20","updateUser":"niewanjun","updateTime":"2022-02-22 17:00:32","tenantId":1,"moduleCategoryId":"","multipleAnalysisId":"","chartName":"明细表","chartEnName":"LIST_TABLE","chartDescription":"","chartTips":"明细表:","chartTypeId":"3","componentCategoryId":"5","componentCategoryName":"分类4","callCount":0,"params":{"chartType":3,"dataId":1,"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"measures":[],"globalFilter":[],"name":"折线图测试","pageNum":1,"pageSize":10,"timeStamp":1645690110747,"type":1},"quoteChartId":138,"componentPageId":"widget94350"},"loading":false,"filterKeys":[],"updateComponent":2,"updateComponentTitle":0,"isPreview":false},"type":"myAnalysis","key":"widget94350"}],"pageSetting":{"width":1300,"height":700,"title":"大数据可视化看板","backgroundColor":"#e1dfdf","backgroundImage":"","backgroundSize":"100% 100%","backgroundPosition":"center center","backgroundRepeat":"repeat","globalTitleStyle":{"fontFamily":""},"isGrid":false}}',
          status: 0,
          publishTime: '',
          del: 0,
          createUser: 'niewanjun',
          createTime: '2022-02-18 16:36:56',
          updateUser: 'admin',
          updateTime: '2022-02-24 16:06:50',
          itemList: [
            {
              id: 463,
              quoteChartId: 142,
              dasDashboardId: 39,
              name: '测试432432',
              type: 2,
              componentType: 1,
              categoryId: 2,
              datasourceId: 105,
              tableName: 'zt_rk_xsb',
              tableCode: 'zt_rk_xsb40',
              databaseName: 'default',
              dataGradeThematicId: 5,
              chartTypeId: 4,
              chartStyle:
                '{"globeStyle":{"data":[],"title":{"name":"柱状图2","style":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":"16px"}},"option":{"xAxis":{"gridIndex":0,"show":true,"position":"bottom","type":"category","name":"","nameTextStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12,"color":"#000000"},"nameLocation":"","data":[],"axisLine":{"show":true},"splitLine":{"show":true},"axisTick":{"show":true,"length":14}},"tooltip":{"trigger":"axis","axisPointer":{"type":"shadow"}},"yAxis":{"show":true,"position":"top","type":"value","name":"","nameLocation":"","nameTextStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12,"color":"#000000"},"axisLine":{"show":true},"splitLine":{"show":true},"axisTick":{"show":true}},"legend":{"show":false,"left":"center","right":"auto","top":"top","bottom":"auto","width":"auto","height":"auto","orient":"horizontal","textStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12}},"series":[],"backgroundColor":"transparent"}},"seriesStyle":{"cgbyfkje":{"label":{"show":true,"position":"top","rotate":0,"offset":[0,0]},"seriesItemStyle":{"opacity":1,"color":"rgba(9,249,157,1)","borderRadius":[0,0,0,0]}}}}',
              chartAxisData:
                '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"timeStamp":1645174345563,"pageNum":1,"pageSize":999999,"chartType":4,"type":1}',
              del: 0,
              componentPageId: 'widget776697',
              createUser: 'admin',
              createTime: '2022-02-24 16:06:50',
              updateUser: 'admin',
              updateTime: '2022-02-24 16:06:50',
              tenantId: 1,
            },
            {
              id: 464,
              quoteChartId: 139,
              dasDashboardId: 39,
              name: '新折线图测试',
              type: 2,
              componentType: 1,
              categoryId: 2,
              datasourceId: 105,
              tableName: 'zt_rk_xsb',
              tableCode: 'zt_rk_xsb40',
              databaseName: 'default',
              dataGradeThematicId: 5,
              chartTypeId: 12,
              chartStyle:
                '{"globeStyle":{"data":[],"title":{"name":"折线图","style":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":"16px"}},"option":{"color":[],"xAxis":{"gridIndex":0,"show":true,"position":"bottom","type":"category","name":"","nameTextStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12,"color":"#000000"},"nameLocation":"","data":[],"axisLine":{"show":true},"splitLine":{"show":true},"axisTick":{"show":true,"length":14}},"tooltip":{"trigger":"axis","axisPointer":{"type":"shadow"}},"yAxis":{"show":true,"position":"top","type":"value","name":"","nameLocation":"","nameTextStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12,"color":"#000000"},"axisLine":{"show":true},"splitLine":{"show":true},"axisTick":{"show":true}},"legend":{"show":false,"left":"center","right":"auto","top":"top","bottom":"auto","width":"auto","height":"auto","orient":"horizontal","textStyle":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":12}},"series":[],"backgroundColor":"transparent"}},"seriesStyle":{"cgbyfkje":{"label":{"show":true,"position":"top","rotate":0,"offset":[0,0]},"seriesItemStyle":{"opacity":1,"color":"#c23531","borderRadius":[0,0,0,0]},"itemStyle":{"opacity":1,"color":"#c23531","borderRadius":[0,0,0,0]}}}}',
              chartAxisData:
                '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"timeStamp":1645173767363,"pageNum":1,"pageSize":999999,"chartType":12,"type":1}',
              del: 0,
              componentPageId: 'widget460767',
              createUser: 'admin',
              createTime: '2022-02-24 16:06:50',
              updateUser: 'admin',
              updateTime: '2022-02-24 16:06:50',
              tenantId: 1,
            },
            {
              id: 465,
              quoteChartId: 140,
              dasDashboardId: 39,
              name: '面积图测试',
              type: 2,
              componentType: 1,
              categoryId: 5,
              datasourceId: 105,
              tableName: 'zt_rk_xsb',
              tableCode: 'zt_rk_xsb40',
              databaseName: 'default',
              dataGradeThematicId: 5,
              chartTypeId: 13,
              chartStyle: '{"globeStyle":"", "seriesStyle":""}',
              chartAxisData:
                '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[{"name":"cgbyfkje","enName":"cgbyfkje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"96","colType":"INT","order":0,"origin":0,"type":2}],"timeStamp":1645145434936,"pageNum":1,"pageSize":999999,"chartType":13,"type":1}',
              del: 0,
              componentPageId: 'widget128255',
              createUser: 'admin',
              createTime: '2022-02-24 16:06:50',
              updateUser: 'admin',
              updateTime: '2022-02-24 16:06:50',
              tenantId: 1,
            },
            {
              id: 466,
              quoteChartId: 136,
              dasDashboardId: 39,
              name: '测试条形图',
              type: 2,
              componentType: 1,
              categoryId: 5,
              datasourceId: 105,
              tableName: 'zt_rk_xsb',
              tableCode: 'zt_rk_xsb40',
              databaseName: 'default',
              dataGradeThematicId: 5,
              chartTypeId: 6,
              chartStyle: '{"globeStyle":"", "seriesStyle":""}',
              chartAxisData:
                '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[{"name":"bycgje","enName":"bycgje","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"95","colType":"INT","order":0,"origin":0,"type":2},{"name":"cp1hk","enName":"cp1hk","numFormat":{"type":1,"digit":0,"unit":1,"suffix":""},"countingRules":1,"id":"97","colType":"INT","order":0,"origin":0,"type":2}],"timeStamp":1645083445300,"pageNum":1,"pageSize":999999,"chartType":6,"type":1}',
              del: 0,
              componentPageId: 'widget448001',
              createUser: 'admin',
              createTime: '2022-02-24 16:06:50',
              updateUser: 'admin',
              updateTime: '2022-02-24 16:06:50',
              tenantId: 1,
            },
            {
              id: 467,
              quoteChartId: 138,
              dasDashboardId: 39,
              name: '折线图测试',
              type: 2,
              componentType: 1,
              categoryId: 5,
              datasourceId: 105,
              tableName: 'zt_rk_xsb',
              tableCode: 'zt_rk_xsb40',
              databaseName: 'default',
              dataGradeThematicId: 5,
              chartTypeId: 3,
              chartStyle:
                '{"globeStyle":{"title":{"name":"明细表2","style":{"fontFamily":"system-ui,-apple-system,BlinkMacSystemFont,segoe ui,Roboto,Helvetica,Arial,sans-serif,apple color emoji,segoe ui emoji,segoe ui symbol","fontSize":"16px"}},"pagination":{"pageSize":20,"current":1,"total":533},"option":{"data":[],"fields":{"columns":[]},"meta":[]}},"seriesStyle":""}',
              chartAxisData:
                '{"dataSource":{"databaseName":"default","datasourceId":105,"gradeThematicId":5,"tableName":"zt_rk_xsb","tableCode":"zt_rk_xsb40"},"dimensions":[{"name":"gszq","enName":"gszq","countingRules":"","id":"89","colType":"STRING","order":0,"origin":0,"type":1}],"globalFilter":[],"measures":[],"timeStamp":1645520509375,"pageNum":1,"dataId":138,"name":"折线图测试","pageSize":20,"chartType":3,"type":1}',
              del: 0,
              componentPageId: 'widget94350',
              createUser: 'admin',
              createTime: '2022-02-24 16:06:50',
              updateUser: 'admin',
              updateTime: '2022-02-24 16:06:50',
              tenantId: 1,
            },
          ],
          dasLabelList: '',
        },
      ],
      leaf: false,
    },
  ]
  throw new Success(data)
})

export default router
